"""add mob number for user

Revision ID: 6e6e1ed63ff0
Revises: 51d2ce3c42fb
Create Date: 2026-02-20 12:41:05.861430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e6e1ed63ff0'
down_revision: Union[str, Sequence[str], None] = '51d2ce3c42fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mob_number', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mob_number')
    # ### end Alembic commands ###
