"""create follower table

Revision ID: 726967ceaec3
Revises: 51d2ce3c42fb
Create Date: 2026-02-21 12:45:30.465317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '726967ceaec3'
down_revision: Union[str, Sequence[str], None] = '51d2ce3c42fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('followed_uid', sa.Integer(), nullable=False),
    sa.Column('follower_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_uid'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_uid'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('followed_uid', 'follower_uid', name='followers_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow_list')
    # ### end Alembic commands ###
