"""add comment user id column

Revision ID: afbed4e7efd0
Revises: e6be246480e3
Create Date: 2026-02-22 23:11:22.450997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afbed4e7efd0'
down_revision: Union[str, Sequence[str], None] = 'e6be246480e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_comments', sa.Column('comment_uid', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'post_comments', 'users', ['comment_uid'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_comments', type_='foreignkey')
    op.drop_column('post_comments', 'comment_uid')
    # ### end Alembic commands ###
