"""add created_at in follower table

Revision ID: ffd0d256f3c8
Revises: 726967ceaec3
Create Date: 2026-02-21 12:48:57.609062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffd0d256f3c8'
down_revision: Union[str, Sequence[str], None] = '726967ceaec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow_list', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('follow_list', 'created_at')
    # ### end Alembic commands ###
